### ISSUE TITLE
Split NetteExtension to each component into separate bridges in backwards compatible way

### ISSUE THREAD

**Issue by fprochazka** [nette/bootstrap#4]
- [x] database @hrach 
- [x] cache @dg
- [ ] http @xificurk 
- [ ] tracy @xificurk  
- [x] mail @xificurk  
- [x] application @dg 
- [x] routing @dg 
- [ ] security
- [ ] forms
- [x] latte @xificurk 
- [ ] container

**Comment by xificurk** [comment]
This should be imho resolved before releasing v2.3...
ping @dg
