### ISSUE TITLE
Setup DI container parent class

### ISSUE THREAD

**Issue by BilboTav** [nette/bootstrap#52]
It was possible through specific parameters in Nette 2.3, why it was removed?
Is it possible somehow?

I have this piece of code implemented, which does what I need, but it is ugly hack. I would prefer a clean way.

```
	public function generateContainer(DI\Compiler $compiler)
	{
		$containerCode = parent::generateContainer($compiler);
		if (isset($this->containerParentClass)) {
			// Hack :-(
			$containerCode = str_replace('extends ' . DI\Container::class, 'extends ' . $this->containerParentClass, $containerCode);
		}

		return $containerCode;
	}
```

**Comment by dg** [comment]
It should be done by compiler extension. Can you send PR for https://github.com/nette/di/blob/master/src/DI/Extensions/DIExtension.php?
