### ISSUE TITLE
Detect debugMode by IP behind proxy or in docker container

### ISSUE THREAD

**Issue by f3l1x** [nette/bootstrap#54]
- bug report? unknown
- feature request? unknown
- version: 2.4.3

### Description

This is how code looks like:

https://api.nette.org/2.4/source-Bootstrap.Configurator.php.html#_detectDebugMode

```php
	public static function detectDebugMode($list = NULL): bool
	{
		$addr = $_SERVER['REMOTE_ADDR'] ?? php_uname('n');
		$secret = is_string($_COOKIE[self::COOKIE_SECRET] ?? NULL)
			? $_COOKIE[self::COOKIE_SECRET]
			: NULL;
		$list = is_string($list)
			? preg_split('#[,\s]+#', $list)
			: (array) $list;
		if (!isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
			$list[] = '127.0.0.1';
			$list[] = '::1';
		}
		return in_array($addr, $list, TRUE) || in_array("$secret@$addr", $list, TRUE);
	}
```

Let's say we have a proxy in one docker container and webserver in second one. 
`$_SERVER['REMOTE_ADDR']` is IP of the docker proxy container, so it's impossible to use `$configurator->setDebugMode(['ip1', 'ip2'])`, because it's never matched againts real guest IP address.

Am I doing something wrong or we should change the first line to:

```php
if (isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
   $addr = $_SERVER['HTTP_X_FORWARDED_FOR'];
} else {
    $addr = $_SERVER['REMOTE_ADDR'] ?? php_uname('n');
}
```

**Comment by enumag** [comment]
```php
$addr = $_SERVER['HTTP_X_FORWARDED_FOR'] ?? $_SERVER['REMOTE_ADDR'] ?? php_uname('n');
```

**Comment by f3l1x** [comment]
@enumag Well, sure. I wanna show the difference on the first look ;-) :eye:

**Comment by xificurk** [comment]
You cannot rely on `$_SERVER['HTTP_X_FORWARDED_FOR']` - client may send whatever they want in this header.
Sure, in your specific case (app in docker behind proxy) it won't be a problem, but consider app that's not running behind any proxy - if you enable debug mode e.g. for IP `1.2.3.4` then anyone can enable it simply by sending a request with `X-Forwarded-For: 1.2.3.4` header.

**Comment by f3l1x** [comment]
@xificurk Oh, I'm too long in docker environment that I've forgot about the rest cases. :-)

What do you suggest?

**Comment by f3l1x** [comment]
@hrach @JanTvrdik Any other hints better then :-1:?

**Comment by xificurk** [comment]
I think we could use something along the lines of:
```
if (isset($_SERVER['REMOTE_ADDR'])) {
	$addr = $_SERVER['REMOTE_ADDR'];
	if (isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
		$addr =  $_SERVER['HTTP_X_FORWARDED_FOR'] . ',' . $addr;
	}
} else {
	$addr = php_uname('n');
}
```

This should be backward compatible, unless you currently rely on the fact that `REMOTE_ADDR` contains some proxy address and you want to enable debug mode for all clients that use it (which I think you should avoid anyway).
You could then enable debug mode by specifying the whole chain of addresses client-proxy(-proxy...).

**Comment by f3l1x** [comment]
The thing is when do you use Rancher, you cannot rely on IP because every container has different one. Each deploy generates different one. 

I have to think about some token-based debug mode.

**Comment by Majkl578** [comment]
@f3l1x Random like absolutely random or random from a specific range? Because if it was always i.e. from 172.17.0.1-172.31.255.255, then you could whitelist 172.17.0.0/19.

**Comment by f3l1x** [comment]
Random from specific range, you're right.

For example:
- 10.42.55.133
- 10.42.96.32
- 10.42.154.131

But problem is how to detect your IP behind this proxy. Because `Configurator` does not support IP-range (https://api.nette.org/2.4/source-Bootstrap.Configurator.php.html#375-396).

**Comment by f3l1x** [comment]
I think it's not problem of nette/bootstrap and I solved it otherwisly (something like https://github.com/nette/tracy/issues/297#issuecomment-400051225). So I am closing it. :-)

**Comment by farazpartoei** [comment]
this configuration worked for me

`ports: 
  - mode: host 
    protocol: tcp 
    published: 8082 
    target: 80`

changing port bind mode to host

how ever you should force your fronted container to run on the specific host in swarm cluster only

i.e.
```
deploy: 
  placement: 
    constraints: 
      [node.role == manager]
```
