### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by aleswita** [nette/bootstrap#58]
What is wrong?
![Výstřižek](https://user-images.githubusercontent.com/6991688/55029047-67eca300-5009-11e9-800a-98f68b78c5cd.PNG)

**Comment by ostrolucky** [comment]
Should be solved by now, 3.0.0 has been released 25 days ago

**Comment by milo** [comment]
`nette/boostrap` `v3.0.0` has been released on 26.3.2019
