### ISSUE TITLE
Incompability with Tracy\Tracy < 2.5

### ISSUE THREAD

**Issue by JanMikes** [nette/bootstrap#60]
Hello, i was just trying to update nette to 3.0 and encountered this issue. Of course i am willing to upgrade tracy/tracy too, but i do not think this is expected behaviour :-). 

Version: 3.0

### Bug Description
Exception `Class 'Tracy\Bridges\Nette\Bridge' not found` occurs when trying to run application.

### Steps To Reproduce
Install tracy 2.4.* and nette/boostrap 3.0

### Expected Behavior
I would expect that composer does not allow me to install incompatible versions with each other.

### Possible Solution
I suggest adding conflict of tracy < 2.5 to composer.json

<img width="858" alt="Screenshot 2019-09-30 08 46 52" src="https://user-images.githubusercontent.com/3995003/65855199-e03c7400-e35e-11e9-9e6a-d21a812647f6.png">

**Comment by JanTvrdik** [comment]
> I suggest adding conflict of tracy < 2.5 to composer.json

That will just make you install older version of nette bootstrap. Or not?

**Comment by JanMikes** [comment]
> That will just make you install older version of nette bootstrap. Or not?

Well, it depends - if i explicitly specify version in composer.json `nette/bootstrap: "~3.0.0"` but still will keep my old `tracy/tracy: "~2.4.9"` it will fail on composer level and will not allow me to install newer nette/bootstrap.

**Comment by JanMikes** [comment]
Thank you @dg this was superfast 👍
