### ISSUE TITLE
The default parameter values are incorrectly determined when calling Nette Application as a Composer script

### ISSUE THREAD

**Issue by janbarasek** [nette/bootstrap#67]
Version: v3.0.2

### Bug Description
Hello,

If Nette starts in CLI mode other than via `index.php` (for example via Composer), the default parameter values will be set incorrectly.

![Snímek obrazovky 2020-09-17 v 18 51 58](https://user-images.githubusercontent.com/4738758/93504021-2a748780-f919-11ea-911f-e4b6adf2ff98.png)

Sample config in `composer.json` ([live example](https://github.com/baraja-core/sandbox/blob/5c32e8534100807206bbcf99ed36e43e39bb07c0/composer.json#L59)):

```json
"scripts": {
	"post-autoload-dump": "Baraja\\PackageRegistrator\\PackageRegistrator::composerPostAutoloadDump"
}
```

The problem occurs in `index.php` detection via `ReflectionClass` and `debug_backtrace()` function:

![Snímek obrazovky 2020-09-17 v 18 53 02](https://user-images.githubusercontent.com/4738758/93504150-64de2480-f919-11ea-9cb8-783f6b3fda8d.png)

Because first item in callstack is not `index.php`, but internal Composer script:

![Snímek obrazovky 2020-09-17 v 19 04 30](https://user-images.githubusercontent.com/4738758/93504211-77585e00-f919-11ea-923e-8cd41c2ff54b.png)

[Booting logic is here](https://github.com/baraja-core/package-manager/blob/bc74fa7d99bdbf555ce517013086a832f8965f04/src/InteractiveComposer/BaseTask.php#L51).

### Steps To Reproduce
Run Nette application via Composer `post-autoload-dump` script when `index.php` is not first called script.

### Expected Behavior
Correct parameter values like in normal CLI mode.

### Possible Solution
In CLI mode, when the Composer is called, the base path should be detected differently. For example, via `ReflectionClass` over the Booting class, or by searching the index.php file. In case of error, paths can also be estimated from`appDir`, which is usually correct.

I was thinking about how to fix the error, but I didn't come up with any reasonable solution.

Thanks.

**Comment by janbarasek** [comment]
Possible solution: https://github.com/baraja-core/package-manager/commit/54d5cea2881e80e36ad87db592182585e8a1f007

**Comment by JanTvrdik** [comment]
If your setup is non-standard, you are expected to provide the values explicitly.
